### ISSUE TITLE
TypeScript lib checking errors using this module

### ISSUE THREAD

**Issue by TheAkio** [sindresorhus/builtin-modules#10]
I'm using the latest TypeScript version 3.5.3 and I'm getting the following errors:

`node_modules/builtin-modules/index.d.ts(12,40): error TS1005: ',' expected.`
`node_modules/builtin-modules/index.d.ts(12,46): error TS1005: ',' expected.`

The import I'm using is `import * as builtinModules from 'builtin-modules';` and the option `skipLibCheck` is disabled so the compiler is checking for correct typing files.

The line it complains about is the following:

`declare const builtinModules: readonly string[];`

It looks like the reason is that the `const` is additionally declared as `readonly` which TypeScript apperantly doesn't like. Removing the `readonly` fixes the error for me.

**Comment by sindresorhus** [comment]
We have type tests that are passing with the latest TS: https://github.com/sindresorhus/builtin-modules/blob/master/index.test-d.ts

**Comment by TheAkio** [comment]
Oh, looks like it was my bad. I was running `tsc` manually which was using the global version which was still on `3.3.3333`. Updated it and it worked again.

Sorry for the inconvenience.
