### ISSUE TITLE
The list is unneeded

### ISSUE THREAD

**Issue by cobaltt7** [sindresorhus/builtin-modules#14]
```js
const builtin = require('module').builtinModules;
```

https://github.com/nodejs/node/blob/master/doc/api/module.md#modulesyncbuiltinesmexports

**Comment by sindresorhus** [comment]
This issue is unneeded

**Comment by sindresorhus** [comment]
If you look at the source and also read the readme you'll see that this filters out deprecated modules and also provides a static list.
