### ISSUE TITLE
Why is 'wasi' module not displayed?

### ISSUE THREAD

**Issue by Neos21** [sindresorhus/builtin-modules#16]
I have a small question.
When I use the package, the `wasi` module was not included in the list.
But the `builtin-modules.json` is including it.
What is this difference?

**Comment by Neos21** [comment]
My environment:

- MacBook Pro 16-inch 2019
- Node.js v18.5.0

```
$ sw_vers
ProductName:    macOS
ProductVersion: 12.4
BuildVersion:   21F79

$ node -v
v18.5.0

$ npm -v
8.12.1
```

**Comment by sindresorhus** [comment]
It requires the `--experimental-wasi-unstable-preview1` flag per Node.js docs.
