### ISSUE TITLE
Update list?

### ISSUE THREAD

**Issue by piranna** [sindresorhus/builtin-modules#3]
List is frm 3 years old, maybe it would be possible to update it and configure an automated process to keep it updated with latest versions? :-)

**Comment by sindresorhus** [comment]
Updated now. If you need something that is always up to date, just use the main API instead of the static list. The static list is updated on request. New Node.js APIs are not added very often, so not worth automating it.

**Comment by piranna** [comment]
Thanks for that. Doc was not clear to me and though it was using a static generated list, sorry. Anyway it got updated, so it can be useful to others too :-)

**Comment by trusktr** [comment]
> just use the main API

How do we use the "main API" to get a list at runtime?

**Comment by trusktr** [comment]
In case anyone stumbles here, this is Node.js API for querying the list of all builtin modules:

```js
const builtin = require('module').builtinModules;
```

and example of the output in Node repl:

```js
> require('module').builtinModules
[
  '_http_agent',       '_http_client',        '_http_common',
  '_http_incoming',    '_http_outgoing',      '_http_server',
  '_stream_duplex',    '_stream_passthrough', '_stream_readable',
  '_stream_transform', '_stream_wrap',        '_stream_writable',
  '_tls_common',       '_tls_wrap',           'assert',
  'async_hooks',       'buffer',              'child_process',
  'cluster',           'console',             'constants',
  'crypto',            'dgram',               'dns',
  'domain',            'events',              'fs',
  'http',              'http2',               'https',
  'inspector',         'module',              'net',
  'os',                'path',                'perf_hooks',
  'process',           'punycode',            'querystring',
  'readline',          'repl',                'stream',
  'string_decoder',    'sys',                 'timers',
  'tls',               'trace_events',        'tty',
  'url',               'util',                'v8',
  'vm',                'worker_threads',      'zlib'
]
```

The doc for that (including supported Node versions) is [here](https://nodejs.org/api/modules.html#modules_module_builtinmodules).
