### ISSUE TITLE
require('repl')._builtinLibs

### ISSUE THREAD

**Issue by chrisdothtml** [sindresorhus/builtin-modules#6]
```javascript
require('repl')._builtinLibs
```

I've used this in a lot of my rollup builds to exclude node builtins. Looks like it works as far back as node v0.1.3

https://runkit.com/chrisdothtml/builtin-libs

**Comment by sindresorhus** [comment]
See the open PR.

**Comment by chrisdothtml** [comment]
Ah, fair enough
